CC= cl
DEFS=  -DWINNT=1

INCLUDES=  -I.
LIBRARY= at.lib

# replace -O with -g in order to debug

DEFINES= $(INCLUDES) $(DEFS) 
#CFLAGS=  $(cvars) $(cdebug) -nologo -G4 $(DEFINES)


SRCS = at.c 
OBJS = at.obj 

.c.obj:
	$(CC) $(CFLAGS) $(DEFS) -c $< -Fo$@

all: $(LIBRARY)

$(LIBRARY): $(OBJS)
	link /lib /OUT:$(LIBRARY) $(OBJS) 

clean:
	del $(OBJS) $(LIBRARY) *.bak

